version: '3.9'
services:
  apache:
    image: httpd:latest
    container_name: apache-app-config
    volumes:
      - ./configs:/usr/local/apache2/htdocs
    environment:
      VIRTUAL_HOST: appconfig.biogateway.eu
      LETSENCRYPT_HOST: appconfig.biogateway.eu
      VIRTUAL_PORT: 80