version: '3.9'
services:
  apache:
    image: httpd:latest
    container_name: apache-app-config
    volumes:
      - ./httpd.conf:/usr/local/apache2/conf/httpd.conf
      - ./configs:/usr/local/apache2/htdocs
    environment:
      VIRTUAL_HOST: appconfig.biogateway.eu
      LETSENCRYPT_HOST: appconfig.biogateway.eu
      VIRTUAL_PORT: 80
    networks:
      nginx_network:
networks:
  nginx_network:
    external: true