
services:
  apache:
    image: httpd:latest
    container_name: apache-app-config
    volumes:
      - ./httpd.conf:/usr/local/apache2/conf/httpd.conf
      - ./configs:/usr/local/apache2/htdocs
    ports:
      - "${HTTP_PORT}:80"
